imdb_id: tt3152624
title: Trainwreck (2015)
cast:
- sequence: 0
  person_imdb_id: tt0703800
  name: Colin Quinn
  roles:
  - Gordon
  notes: ''
- sequence: 1
  person_imdb_id: tt6477291
  name: Devin Fabry
  roles:
  - Nine Year Old Amy
  notes: ''
- sequence: 2
  person_imdb_id: tt7106491
  name: Carla Oudin
  roles:
  - Five Year Old Kim
  notes: ''
- sequence: 3
  person_imdb_id: tt2154960
  name: Amy Schumer
  roles:
  - Amy
  notes: ''
- sequence: 4
  person_imdb_id: tt2019219
  name: Josh Segarra
  roles:
  - Staten Island Oli
  notes: ''
- sequence: 5
  person_imdb_id: tt3261682
  name: Ryan Farrell
  roles:
  - One-Night Stand Guy
  notes: ''
- sequence: 6
  person_imdb_id: tt7106492
  name: Robert E. Torres
  roles:
  - One-Night Stand Guy
  notes: ''
- sequence: 7
  person_imdb_id: tt1184886
  name: Jim Florentine
  roles:
  - One-Night Stand Guy
  notes: ''
- sequence: 8
  person_imdb_id: tt0446218
  name: Robert Kelly
  roles:
  - One-Night Stand Guy
  notes: (as Bobby Kelly)
- sequence: 9
  person_imdb_id: tt4522036
  name: Dan Soder
  roles:
  - Dumpster Guy
  notes: ''
- sequence: 10
  person_imdb_id: tt1078479
  name: John Cena
  roles:
  - Steven
  notes: ''
- sequence: 11
  person_imdb_id: tt0040995
  name: Dave Attell
  roles:
  - Noam
  notes: ''
- sequence: 12
  person_imdb_id: tt3364779
  name: Vanessa Bayer
  roles:
  - Nikki
  notes: ''
- sequence: 13
  person_imdb_id: tt0842770
  name: Tilda Swinton
  roles:
  - Dianna
  notes: ''
- sequence: 14
  person_imdb_id: tt1320827
  name: Randall Park
  roles:
  - Bryson
  notes: ''
- sequence: 15
  person_imdb_id: tt0321835
  name: Jon Glaser
  roles:
  - Schultz
  notes: ''
- sequence: 16
  person_imdb_id: tt3009232
  name: Ezra Miller
  roles:
  - Donald
  notes: ''
- sequence: 17
  person_imdb_id: tt0488953
  name: Brie Larson
  roles:
  - Kim
  notes: ''
- sequence: 18
  person_imdb_id: tt5057971
  name: Evan Brinkman
  roles:
  - Allister
  notes: ''
- sequence: 19
  person_imdb_id: tt1898126
  name: Mike Birbiglia
  roles:
  - Tom
  notes: ''
- sequence: 20
  person_imdb_id: tt0516093
  name: Norman Lloyd
  roles:
  - Norman
  notes: ''
- sequence: 21
  person_imdb_id: tt0352778
  name: Bill Hader
  roles:
  - Aaron
  notes: ''
- sequence: 22
  person_imdb_id: tt1429908
  name: LeBron James
  roles:
  - LeBron James
  notes: ''
- sequence: 23
  person_imdb_id: tt0705356
  name: Daniel Radcliffe
  roles:
  - The Dogwalker
  notes: ''
- sequence: 24
  person_imdb_id: tt0000673
  name: Marisa Tomei
  roles:
  - The Dog Owner
  notes: ''
- sequence: 25
  person_imdb_id: tt0732804
  name: Keith Robinson
  roles:
  - Guy in Back of Theater
  notes: ''
- sequence: 26
  person_imdb_id: tt1705625
  name: Marina Franklin
  roles:
  - Woman in Back of Theater
  notes: ''
- sequence: 27
  person_imdb_id: tt1953290
  name: Dave Hanson
  roles:
  - Alice's Tea Cup Waiter
  notes: ''
- sequence: 28
  person_imdb_id: tt0203457
  name: Pete Davidson
  roles:
  - Dr. Conner's Patient
  notes: ''
- sequence: 29
  person_imdb_id: tt5671708
  name: Kim Caramele
  roles:
  - S'nuff Receptionist
  notes: ''
- sequence: 30
  person_imdb_id: tt0541218
  name: Method Man
  roles:
  - Temembe
  notes: (as Cliff 'Method Man' Smith)
- sequence: 31
  person_imdb_id: tt0018614
  name: Max Alexander
  roles:
  - Max the Wheelchair Orderly
  notes: ''
- sequence: 32
  person_imdb_id: tt7106493
  name: Criscia Richardson
  roles:
  - Injured Knicks City Dancer
  notes: ''
- sequence: 33
  person_imdb_id: tt5307166
  name: Claudia O'Doherty
  roles:
  - Wendy
  notes: ''
- sequence: 34
  person_imdb_id: tt1178424
  name: Kyle Dunnigan
  roles:
  - Kyle
  notes: ''
- sequence: 35
  person_imdb_id: tt1985893
  name: Kevin Kane
  roles:
  - Kevin
  notes: ''
- sequence: 36
  person_imdb_id: tt0005218
  name: Tim Meadows
  roles:
  - Tim
  notes: ''
- sequence: 37
  person_imdb_id: tt3218751
  name: Nikki Glaser
  roles:
  - Lisa
  notes: ''
- sequence: 38
  person_imdb_id: tt3008608
  name: Bridget Everett
  roles:
  - Kat
  notes: ''
- sequence: 39
  person_imdb_id: tt0157917
  name: Alva Chinn
  roles:
  - Benefit Guest
  notes: ''
- sequence: 40
  person_imdb_id: tt1842307
  name: Arnold Y. Kim
  roles:
  - Benefit Guest
  notes: (as Arnold Kim)
- sequence: 41
  person_imdb_id: tt1632493
  name: Rob Buntzen
  roles:
  - Benefit Guest
  notes: ''
- sequence: 42
  person_imdb_id: tt5286404
  name: Karen Chamberlain
  roles:
  - Awards Luncheon Coordinator
  notes: ''
- sequence: 43
  person_imdb_id: tt0576538
  name: Ajay Mehta
  roles:
  - Dr. Raj
  notes: ''
- sequence: 44
  person_imdb_id: tt2561320
  name: Tony Romo
  roles:
  - Tony Romo
  notes: ''
- sequence: 45
  person_imdb_id: tt2535778
  name: Amar'e Stoudemire
  roles:
  - Amar'e Stoudemire
  notes: ''
- sequence: 46
  person_imdb_id: tt2287597
  name: Rachel Feinstein
  roles:
  - Nurse Rachel
  notes: ''
- sequence: 47
  person_imdb_id: tt3953449
  name: Victoria Dicce
  roles:
  - Donald's Mother
  notes: ''
- sequence: 48
  person_imdb_id: tt5665312
  name: Lisa K. Price
  roles:
  - Woman on Bench with One-Hitter
  notes: (as Lisa Kicielinski)
- sequence: 49
  person_imdb_id: tt0000111
  name: Matthew Broderick
  roles:
  - Matthew Broderick
  notes: ''
- sequence: 50
  person_imdb_id: tt0016548
  name: Marv Albert
  roles:
  - Marv Albert
  notes: ''
- sequence: 51
  person_imdb_id: tt0263708
  name: Chris Evert
  roles:
  - Chris Evert
  notes: ''
- sequence: 52
  person_imdb_id: tt0860384
  name: Kevin Thompson
  roles:
  - Vanity Fair Editor
  notes: ''
- sequence: 53
  person_imdb_id: tt0428656
  name: Leslie Jones
  roles:
  - Angry Subway Patron
  notes: ''
- sequence: 54
  person_imdb_id: tt1369978
  name: Estee Adoram
  roles:
  - Jostled Subway Patron
  notes: ''
- sequence: 55
  person_imdb_id: tt3678814
  name: Roger Brenner
  roles:
  - Fredderick the Anesthesiologist
  notes: (uncredited)
- sequence: 56
  person_imdb_id: tt5682728
  name: José Báez
  roles:
  - Park Goer
  - Commuter
  notes: ''
- sequence: 57
  person_imdb_id: tt1919573
  name: Tony Cheng
  roles:
  - Asian Bartender
  notes: (uncredited)
- sequence: 58
  person_imdb_id: tt5538442
  name: Jessica Cherniak
  roles:
  - Benefit Guest
  notes: (uncredited)
- sequence: 59
  person_imdb_id: tt3317479
  name: Marmee Regine Cosico
  roles:
  - ND Theater Pedestrian
  notes: (uncredited)
- sequence: 60
  person_imdb_id: tt6635864
  name: Jedidiah Dore
  roles:
  - Slam Dunk Fan
  notes: (uncredited)
- sequence: 61
  person_imdb_id: tt7055008
  name: Christine Duke
  roles:
  - Courtside Fan
  notes: (uncredited)
- sequence: 62
  person_imdb_id: tt0243637
  name: Tim Duquette
  roles:
  - Gordon's Sad Ol' Pal at Funeral
  notes: (uncredited)
- sequence: 63
  person_imdb_id: tt6928525
  name: Scott Eliasoph
  roles:
  - Slam Dunk Staff
  notes: (uncredited)
- sequence: 64
  person_imdb_id: tt5007568
  name: Damon C. Fields
  roles:
  - Basketball Fan
  notes: (uncredited)
- sequence: 65
  person_imdb_id: tt5952641
  name: Henry Gagliardi
  roles:
  - Amy's son
  notes: (uncredited)
- sequence: 66
  person_imdb_id: tt6199363
  name: Booker Garrett
  roles:
  - Walk of Shame
  notes: (uncredited)
- sequence: 67
  person_imdb_id: tt3118198
  name: Robert Z. Grant
  roles:
  - Walk of Shame
  notes: (uncredited)
- sequence: 68
  person_imdb_id: tt6637361
  name: Liam Higgins
  roles:
  - Basketball Fan
  notes: (uncredited)
- sequence: 69
  person_imdb_id: tt3210835
  name: Zac Jaffee
  roles:
  - Movie Goer
  notes: (uncredited)
- sequence: 70
  person_imdb_id: tt4667058
  name: Diane Kimbrell
  roles:
  - Resident in Assisted Living Facility
  notes: (uncredited)
- sequence: 71
  person_imdb_id: tt1527941
  name: Rock Kohli
  roles:
  - Walk of Shame
  notes: (uncredited)
- sequence: 72
  person_imdb_id: tt6719748
  name: Christina Lancaster
  roles:
  - Punk Bar Patron
  notes: (uncredited)
- sequence: 73
  person_imdb_id: tt6888010
  name: Michael Lane
  roles:
  - Slam Dunk Fan
  notes: (uncredited)
- sequence: 74
  person_imdb_id: tt4670418
  name: Parker Madison
  roles:
  - Doctor
  notes: (uncredited)
- sequence: 75
  person_imdb_id: tt2677811
  name: John Mainieri
  roles:
  - Mob Bar Bartender
  notes: (uncredited)
- sequence: 76
  person_imdb_id: tt2113885
  name: Joe Mancini
  roles:
  - Wiseguy
  notes: (uncredited)
- sequence: 77
  person_imdb_id: tt3771828
  name: Sebastian Marocola
  roles:
  - Realm
  notes: (uncredited)
- sequence: 78
  person_imdb_id: tt6257954
  name: Danny L. Martin
  roles:
  - Benefit Guest
  notes: (uncredited)
- sequence: 79
  person_imdb_id: tt0565117
  name: Doris McCarthy
  roles:
  - Assisted Living Resident
  notes: (uncredited)
- sequence: 80
  person_imdb_id: tt3158498
  name: Khalil Muhammad
  roles:
  - Security Guard
  notes: (uncredited)
- sequence: 81
  person_imdb_id: tt7542363
  name: Chase Murray
  roles:
  - Extra
  notes: (uncredited)
- sequence: 82
  person_imdb_id: tt2587316
  name: Leah O'Donnell
  roles:
  - Knicks City Dancer
  notes: (uncredited)
- sequence: 83
  person_imdb_id: tt6560656
  name: Romesh Radhakrishnan
  roles:
  - Slam Dunk Fan
  notes: (uncredited)
- sequence: 84
  person_imdb_id: tt4933231
  name: Eddie K. Robinson
  roles:
  - S'Nuff Magazine Employee
  notes: (uncredited)
- sequence: 85
  person_imdb_id: tt3692708
  name: Michael A. Russo
  roles:
  - Wise Guy
  notes: (uncredited)
- sequence: 86
  person_imdb_id: tt5786060
  name: Robert Sage
  roles:
  - Featured Park Scene
  notes: (uncredited)
- sequence: 87
  person_imdb_id: tt6554706
  name: Edward Sass
  roles:
  - Punk Bar Patron
  notes: (uncredited)
- sequence: 88
  person_imdb_id: tt4803119
  name: Chris Skeries
  roles:
  - Bar Patron
  notes: (uncredited)
- sequence: 89
  person_imdb_id: tt5857409
  name: Holly Stanford-Brown
  roles:
  - Slam Dunk Fan
  notes: (uncredited)
- sequence: 90
  person_imdb_id: tt5634260
  name: Krista Tunnell
  roles:
  - Waitress
  notes: (uncredited)
